CSS File Updates for ConfigPage
Wolven531/simple-cra-app pull request #7
Opened 2021-06-20 19:12 UTC by VincentLeighton

# Author Section
Dr Mundo
## Description

CSS File Updates for Config Page per AWilliam's request.
## Screenshot(s) (if applicable)

## PR Readiness Checklist

- [x] Verified all changes are related to feature described above (no scope creep)
- [x] Checked target and base branch (should be feature branch merging INTO `main`)
- [ ] Added unit tests to cover modified / additional code -----"No test"
- [x] Added assignee

2021-06-20 21:36 UTC, Roughnick commented
So there are CSS files per component, wouldn't we want to have a more central location for all the CSS? So the design stays more consistent as the site gets bigger

2021-06-22 02:02 UTC, Wolven531 commented
We don't yet have a central design, but as common CSS is added, we will add it to the `src/index.css`. In React, CSS is either done in the component code (a la CSS-in-JS), or in sibling CSS files (one per component); this change makes it so that we steer away from CSS-in-JS. 

We're choosing to do that because CSS-in-JS has some performance implications (though minor, they add up over time) and it will be easier to maintain the site style using CSS files. As an added benefit, CSS selectors will be used to link the styles to the elements, and those same selectors can make writing unit tests much easier

2021-06-22 02:05 UTC, Wolven531 requested changes
Leaving a RFC (Request For Changes), but I'm going to commit the changes and approve this PR, then merge it

2021-06-22 02:05 UTC, Wolven531 commented on src/ConfigPage/ConfigPage.css
> +	align-content: center;
I always try to keep my CSS style rules in alphabetic order, so I am going to rewrite these two lines as the following -

```suggestion
	align-content: center;
	align-items: center;
```

2021-06-22 02:05 UTC, Wolven531 commented on src/ConfigPage/ConfigPage.tsx
> +				<Grid item >
There's an extra space here

```suggestion
				<Grid item>
```

2021-06-22 02:06 UTC, Wolven531 requested changes
Minor cleanup

2021-06-22 02:06 UTC, Wolven531 commented on src/ConfigPage/ConfigPage.css
> +.config-page .MuiGrid-item{
Space missing here

```suggestion
.config-page .MuiGrid-item {
```

2021-06-22 02:06 UTC, Wolven531 commented on src/ConfigPage/ConfigPage.css
> +.config-page .center-flex{
Space missing here

```suggestion
.config-page .center-flex {
```

2021-06-22 02:07 UTC, Wolven531 approved these changes
Lgtm, 👍

2021-06-22 02:07 UTC, merged